const experiencesMain = [
  {
    id: 0,
    company: "UNAM - UTICT",
    position: "Software Engineer",
    startDate: new Date("2024-10-04"),
    endDate: "",
    type: "Full Time",
    location: "Remote",
    description: `Led development of mission-critical educational platforms serving thousands of students using both JavaScript and Java ecosystems.\n\n- <strong>Full-Stack Development:</strong> Built scalable applications using Node.js/Express with TypeScript for rapid development and Java Spring Boot for enterprise-grade backend services.\n- <strong>Legacy Integration:</strong> Designed custom XML-to-JSON parser using both Node.js streams and Java SAX processing for complex SOAP integrations.\n- <strong>Testing Strategy:</strong> Implemented comprehensive testing with Jest for JavaScript services and JUnit/Mockito for Java applications, achieving 90%+ coverage.\n- <strong>Performance:</strong> Optimized both JavaScript and Java APIs, reducing response times by 60% through query optimization and caching strategies.\n\n<strong>Impact:</strong> Delivered robust, maintainable systems that handle high traffic loads using the best of both ecosystems.`,
    shortDescription: `Designed and built scalable educational platforms using both JavaScript and Java ecosystems, implementing enterprise engineering practices and optimizing system performance for thousands of users.`,
    image: "../img/unam-logo.png",
    url: "https://www.linkedin.com/school/arvalli-bed-college-vijaynagar/",
    tagIds: [
      "javascript",
      "typescript",
      "java",
      "springboot",
      "nodejs",
      "expressjs",
      "reactjs",
      "docker",
      "aws",
      "mysql",
      "postgresql",
      "git",
      "jest",
      "maven",
    ],
  },
  {
    id: 1,
    company: "Rocket Code",
    position: "Full-Stack Developer | Tech Lead",
    startDate: new Date("2024-7-01"),
    endDate: new Date("2024-12-20"),
    type: "Full Time",
    location: "Remote",
    description: `Built enterprise-grade insurance platform from scratch using both JavaScript and Java technologies, promoted to Tech Lead within 3 months.\n\n- <strong>Architecture:</strong> Designed distributed system with Java Spring Boot microservices for core business logic and Node.js/Express for rapid API development and integration services.\n- <strong>Frontend:</strong> Built Angular applications with TypeScript, implementing role-based logic and modern state management for responsive user interfaces.\n- <strong>Process Engineering:</strong> Created automated tools for code quality using both JavaScript and Java tooling, established CI/CD pipelines with Maven and npm.\n- <strong>Leadership:</strong> Mentored development team of 10+, established coding standards for both JavaScript and Java ecosystems.\n\n<strong>Results:</strong> Reduced deployment time by 70%, improved system reliability, and established engineering excellence culture across both technology stacks.`,
    shortDescription: `Led technical architecture and implementation of enterprise insurance platform using both JavaScript and Java ecosystems, mentoring development team and establishing best practices for scalable full-stack development.`,
    image: "../img/rocket-code-logo.jpeg",
    url: "https://www.linkedin.com/company/the-rocket-code",
    tagIds: [
      "javascript",
      "typescript",
      "java",
      "springboot",
      "nodejs",
      "expressjs",
      "angular",
      "docker",
      "kubernetes",
      "mysql",
      "redis",
      "rabbitmq",
    ],
  },
  {
    id: 2,
    company: "Xocolatl Finance",
    position: "Front-End Developer",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-08-08"),
    type: "Freelance",
    location: "Remote",
    description: `Developed UI for blockchain-based dApp supporting XOC cryptocurrency using modern JavaScript stack.\n\n- <strong>Interface:</strong> Built responsive dashboard, landing page, and transaction flows with Next.js/React/TypeScript.\n- <strong>Wallet Integration:</strong> Enabled MetaMask and other wallet transactions using Web3 libraries.\n- <strong>Blockchain:</strong> Integrated smart contracts via Wagmi/Scaffold for clean UX.\n- <strong>Collaboration:</strong> Worked with backend devs for seamless contract interaction.\n\n<strong>Outcome:</strong> Delivered secure, reliable crypto user experience.`,
    shortDescription: `Developed a seamless blockchain frontend with wallet integration and smart contract connectivity for a dApp based on the XOC cryptocurrency using Next.js and React.`,
    image: "../img/la-dao-logo.jpeg",
    url: "https://www.xocolatl.finance/",
    tagIds: [
      "nextjs",
      "reactjs",
      "typescript",
      "tailwindcss",
      "wagmi",
      "scaffold",
    ],
  },
  {
    id: 3,
    company: "Red Cap",
    position: "Front-End Developer",
    startDate: new Date("2024-10-02"),
    endDate: new Date("2025-04-02"),
    type: "Freelance",
    location: "Remote",
    description: `Enhanced e-commerce platform for premium products using modern JavaScript technologies.\n\n- <strong>Product Pages:</strong> Developed optimized pages focusing on UX and conversion using React.\n- <strong>Content:</strong> Implemented dynamic sections highlighting product benefits with JavaScript.\n- <strong>E-commerce:</strong> Enhanced listings with detailed descriptions and pricing.\n- <strong>UX:</strong> Improved product presentation with clear benefit breakdowns.\n\n<strong>Outcome:</strong> Enhanced platform's ability to communicate product benefits effectively.`,
    shortDescription: `Enhanced e-commerce platform for premium products using React and JavaScript, improving product presentation and user experience for traditional wellness products.`,
    image: "../img/redcap-logo.png",
    url: "https://redcapdev.myshopify.com/",
    tagIds: ["javascript", "reactjs", "shopify"],
  },
  {
    id: 4,
    company: "ICCBR 2024",
    position: "Full-Stack Developer",
    startDate: new Date("2023-01-01"),
    endDate: new Date("2024-02-28"),
    type: "Freelance",
    location: "Remote",
    description: `Modernized global academic conference platform using both JavaScript and Java ecosystems for optimal performance and maintainability.\n\n- <strong>Migration Strategy:</strong> Refactored from legacy PHP to Vue.js frontend and Java Spring Boot backend with microservices architecture.\n- <strong>Security:</strong> Implemented comprehensive security using Spring Security for Java services and JWT authentication for JavaScript APIs.\n- <strong>Payments:</strong> Integrated Stripe payment processing with Java backend services and JavaScript frontend components.\n- <strong>DevOps:</strong> Established CI/CD pipelines using both Maven for Java and npm for JavaScript, deployed with Docker and AWS.\n\n<strong>Impact:</strong> Transformed legacy system into modern, secure, and scalable platform serving global academic community with optimal technology choices.`,
    shortDescription: `Led complete platform modernization for international academic conference using both JavaScript and Java ecosystems, implementing enterprise-grade security, payment systems, and DevOps practices for scalable global operations.`,
    image: "../img/iccbr-2024-logo.png",
    url: "https://iccbr2024.org/",
    tagIds: [
      "javascript",
      "typescript",
      "java",
      "springboot",
      "vuejs",
      "docker",
      "kubernetes",
      "aws",
      "mysql",
      "redis",
      "tailwindcss",
    ],
  },
];

export default experiencesMain;
