const experiences = [
  {
    id: 1,
    company: "Rocket Code",
    position: "Tech Lead",
    startDate: new Date("2024-10-09"),
    endDate: null,
    type: "Full Time",
    location: "Remote",
    description:
      "As a Tech Lead, I manage a team of 8+ developers in both front-end and back-end areas. My responsibilities include resource allocation using Jira, guiding the team through Scrum processes, and providing technical support to resolve key issues. I ensure smooth collaboration and project delivery while mentoring the team.",
    image: "../img/rocket-code-logo.jpeg",
    url: "https://www.linkedin.com/company/the-rocket-code",
    tagIds: ["angular", "javascript", "java", "maven", "springboot"],
  },
  {
    id: 2,
    company: "Rocket Code",
    position: "Full-Stack Developer",
    startDate: new Date("2024-07-09"),
    endDate: new Date("2024-10-09"),
    type: "Full Time",
    location: "Remote",
    description:
      "My main role as a Full-Stack Developer with a primary focus on front-end development using Angular and React (JavaScript) and back-end development with Java SpringBoot and Maven. I am responsible for developing tickets according to the project I am assigned to, as the company rotates projects based on tagIds.",
    image: "../img/rocket-code-logo.jpeg",
    url: "https://www.linkedin.com/company/the-rocket-code",
    tagIds: ["angular", "javascript", "java", "maven", "springboot"],
  },
  {
    id: 3,
    company: "La DAO",
    position: "Front-End Developer",
    startDate: new Date("2024-05-08"),
    endDate: new Date("2024-08-08"),
    type: "Freelance",
    location: "Remote",
    description:
      "My main role as a Front-End Developer, developing the entire interface from scratch for an application to perform transactions on a new smart contract that includes a new cryptocurrency called XOC. Additionally, I was responsible for making pull requests (PR) and resolving merge conflicts as needed.",
    image: "../img/la-dao-logo.jpeg",
    url: "https://www.linkedin.com/company/ladao/",
    tagIds: ["nextjs", "reactjs", "tailwindcss", "wagmi", "scaffold"],
  },
  {
    id: 4,
    company: "Seguros Gutierrez y Arredondo",
    position: "Django Developer",
    startDate: new Date("2024-03-07"),
    endDate: new Date("2024-05-07"),
    type: "Freelance",
    location: "Hibryd",
    description:
      "I developed a data retrieval form using Django and PostgreSQL to streamline the prospect acquisition process and enhance efficiency for the recruitment team. Focus was on seamlessly capturing and storing prospect data to optimize lead management.",
    image: "../img/GrupoGyA.png",
    url: "https://seragentedeseguros.mx/gya",
    tagIds: ["django", "postgresql", "bootstrap"],
  },
  {
    id: 5,
    company: "ICCBR 2024",
    position: "Full-Stack Developer",
    startDate: new Date("2023-07-23"),
    endDate: new Date("2024-04-01"),
    type: "Freelance",
    location: "Remote",
    description:
      "I collaborated in a team to refactor the entire platform, transitioning from PHP to Astro + JavaScript to remove vulnerabilities. My primary focus included building a robust RESTful API for payment processing and email notifications for ticket purchases. Additionally, I contributed to frontend improvements by refactoring and creating UI components.",
    image: "../img/iccbr-2024-logo.png",
    url: "https://iccbr2024.org/",
    tagIds: ["astro", "tailwindcss", "javascript", "nodejs", "prisma"],
  },
  {
    id: 6,
    company: "Jumwork",
    position: "Bubble Developer",
    startDate: new Date("2020-06-18"),
    endDate: new Date("2022-01-05"),
    type: "Full Time",
    location: "Remote",
    description:
      "I worked on developing the platform from scratch. This platform is a marketplace with an integrated chat, auction system, email notifications, and a payment gateway via Stripe. My primary goal was to work on all modules to deliver a functional, responsive platform without any development errors.",
    image: "../img/jumwork-logo.png",
    url: "https://www.jumwork.com",
    tagIds: ["bubble"],
  },
];

export default experiences;
