const experiences = [
  {
    id: 0,
    company: "UNAM - UTICT",
    position: "Software Engineer Mid-Level",
    startDate: new Date("2024-10-04"),
    endDate: "",
    type: "Full Time",
    location: "Remote",
    description: `Led development of two core platforms: student purchase portal and administrative portal. Key challenge: integrating legacy SOAP service with oversized XML responses.\n\n- <strong>Backend:</strong> Built Node.js/Express services with SOLID principles and Swagger API design.\n- <strong>Legacy Integration:</strong> Designed XML-to-JSON parser that became standard for future SOAP work.\n- <strong>Testing:</strong> Delivered 10+ endpoints with Supertest for smooth frontend integration.\n- <strong>Frontend:</strong> Developed React + Vite UI components.\n\n<strong>Impact:</strong> Reduced integration times from hours to minutes, delivered on time, earned internal recognition.`,
    shortDescription: `Developed and integrated scalable APIs for two mission-critical platforms at UNAM. Tackled a complex SOAP/XML challenge with a custom parser, improving efficiency and setting a reusable internal standard.`,
    image: "../img/unam-logo.png",
    url: "https://www.linkedin.com/school/arvalli-bed-college-vijaynagar/",
    tagIds: [
      "javascript",
      "typescript",
      "nodejs",
      "nextjs",
      "docker",
      "aws",
      "mysql",
      "postgresql",
      "git",
    ],
  },
  {
    id: 1,
    company: "Rocket Code",
    position: "Full-Stack Developer | Tech Lead",
    startDate: new Date("2024-7-01"),
    endDate: new Date("2024-12-20"),
    type: "Full Time",
    location: "Remote",
    description: `Built internal insurance platform from scratch. Promoted to Tech Lead within 3 months.\n\n- <strong>Architecture:</strong> Implemented Clean Architecture with Java/Spring Boot for scalability.\n- <strong>Frontend:</strong> Built Angular 18 UIs with PrimeNG and role-based logic.\n- <strong>Process:</strong> Created GPT-based tool for Conventional Commits, adopted company-wide.\n- <strong>Leadership:</strong> Mentored 10 devs, fostered accountability and trust.\n\n<strong>Results:</strong> Cut delivery time by 3–7 days, standardized workflows, gained leadership trust.`,
    shortDescription: `Led technical execution of an internal insurance platform. Designed scalable architecture, mentored devs, and introduced process improvements that shaped team workflows.`,
    image: "../img/rocket-code-logo.jpeg",
    url: "https://www.linkedin.com/company/the-rocket-code",
    tagIds: [
      "angular",
      "typescript",
      "javascript",
      "java",
      "maven",
      "springboot",
      "mysql",
    ],
  },
  {
    id: 2,
    company: "Xocolatl Finance",
    position: "Front-End Developer",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-08-08"),
    type: "Freelance",
    location: "Remote",
    description: `Developed UI for blockchain-based dApp supporting XOC cryptocurrency.\n\n- <strong>Interface:</strong> Built responsive dashboard, landing page, and transaction flows with Next.js/React/Tailwind.\n- <strong>Wallet Integration:</strong> Enabled MetaMask and other wallet transactions.\n- <strong>Blockchain:</strong> Integrated smart contracts via Wagmi/Scaffold for clean UX.\n- <strong>Collaboration:</strong> Worked with backend devs for seamless contract interaction.\n\n<strong>Outcome:</strong> Delivered secure, reliable crypto user experience.`,
    shortDescription: `Developed a seamless blockchain frontend with wallet integration and smart contract connectivity for a dApp based on the XOC cryptocurrency.`,
    image: "../img/la-dao-logo.jpeg",
    url: "https://www.xocolatl.finance/",
    tagIds: ["nextjs", "reactjs", "tailwindcss", "wagmi", "scaffold"],
  },
  {
    id: 3,
    company: "Red Cap",
    position: "Front-End Developer",
    startDate: new Date("2024-10-02"),
    endDate: new Date("2025-04-02"),
    type: "Freelance",
    location: "Remote",
    description: `Enhanced e-commerce platform for premium products.\n\n- <strong>Product Pages:</strong> Developed optimized pages focusing on UX and conversion.\n- <strong>Content:</strong> Implemented dynamic sections highlighting product benefits.\n- <strong>E-commerce:</strong> Enhanced listings with detailed descriptions and pricing.\n- <strong>UX:</strong> Improved product presentation with clear benefit breakdowns.\n\n<strong>Outcome:</strong> Enhanced platform's ability to communicate product benefits effectively.`,
    shortDescription: `Enhanced e-commerce platform for premium products, improving product presentation and user experience for traditional wellness products.`,
    image: "../img/redcap-logo.png",
    url: "https://redcapdev.myshopify.com/",
    tagIds: ["javascript", "shopify"],
  },
  {
    id: 4,
    company: "ICCBR 2024",
    position: "Full-Stack Developer",
    startDate: new Date("2023-01-01"),
    endDate: new Date("2024-02-28"),
    type: "Freelance",
    location: "Remote",
    description: `Modernized global academic conference platform.\n\n- <strong>Migration:</strong> Refactored from PHP to Astro (frontend) and NestJS/Prisma (backend).\n- <strong>Security:</strong> Redesigned architecture with injection-proof queries.\n- <strong>Payments:</strong> Integrated Stripe for ticket purchases.\n- <strong>DevOps:</strong> Deployed with AWS and automated CI/CD.\n\n<strong>Impact:</strong> Improved maintainability, enabled secure payments, accelerated delivery.`,
    shortDescription: `Led a tech refresh for ICCBR 2024, upgrading its platform stack and implementing payment and deployment systems to production standards.`,
    image: "../img/iccbr-2024-logo.png",
    url: "https://iccbr2024.org/",
    tagIds: [
      "javascript",
      "typescript",
      "nestjs",
      "prisma",
      "aws",
      "astro",
      "tailwindcss",
    ],
  },
];

export default experiences;
